#!/usr/bin/env bash

TOP="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

ensure_line() {
	if ! grep -q "$1" "$2"; then
		echo "$1" >> "$2"
	fi
}

upgrade_system () {
	sudo apt update
	sudo apt -y upgrade
}

install_go () {
	sudo snap install go --channel=1.14/stable --classic
}

install_docker () {
	sudo apt-get install -y curl
	sh -c "$(curl -sSL https://get.docker.com/)"
	sudo usermod -aG docker "${USER}"
	sudo curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
	sudo chmod +x /usr/local/bin/docker-compose
}

install_chrome() {
	sudo snap install chromium
}

install_common_apps () {
	sudo apt install -y vim byobu git curl snapd gnome-tweaks htop net-tools nmap sshfs
	
	sudo snap install spotify
	sudo snap install code --classic
	sudo snap install rambox
	sudo snap install keepassxc
	sudo snap install goland --classic
	sudo snap install pycharm-professional --classic
}

install_zsh () {
	sudo apt install -y git zsh ranger
	
	if [ ! -d $HOME/zsh-config ]; then
		git clone https://bitbucket.org/Vifon/zsh-config.git $HOME/zsh-config
	fi

	cd $HOME/zsh-config
	git submodule update --init
	./install.sh
	

	if [ "$(basename $(echo $SHELL))" != "zsh" ]; then
		chsh -s $(which zsh)
	fi

	if [ ! -d $HOME/.fzf ]; then
		git clone --depth 1 https://github.com/junegunn/fzf.git $HOME/.fzf
	fi
	~/.fzf/install --all
	[ ! -f $HOME/.zshrc.local ] && cp $TOP/.zshrc.local $HOME/.zshrc.local
        cd $(dirname $(readlink -f ~/.zshrc))
        git apply $TOP/zshrc.patch || true

}

for opt in "$@"; do
  case $opt in
    --upgrade)
      upgrade_system
      ;;
    --common)
      install_common_apps
      ;;
    --go)
      install_go
      ;;
    --docker)
      install_docker
      ;;
    --chrome)
      install_chrome
      ;;
    --zsh)
      install_zsh
      ;;
  esac
done

