#!/usr/bin/env bash

TOP="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

ensure_line() {
	if ! grep -q "$1" "$2"; then
		echo "$1" >> "$2"
	fi
}

upgrade_system () {
	sudo apt update
	sudo apt -y upgrade
}

install_docker () {
	sudo apt-get remove docker docker-engine docker.io containerd runc
	sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
	curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - && sudo apt-key fingerprint 0EBFCD88
	sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
	sudo apt-get update && sudo apt-get install docker-ce docker-ce-cli containerd.io
	
	sudo usermod -aG docker "${USER}"
	
	sudo curl -L "https://github.com/docker/compose/releases/download/1.28.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
	sudo chmod +x /usr/local/bin/docker-compose
}

install_common_apps () {
	sudo apt install -y snapd vim byobu git curl gnome-tweaks htop net-tools nmap sshfs sshpass
	
	sudo snap install go --channel=1.15/stable --classic
	sudo snap install spotify
	sudo snap install rambox
	sudo snap install code --classic
	sudo snap install pycharm-community --classic
	sudo snap install goland --classic
	sudo snap install chromium
	sudo snap install cura-slicer
	sudo snap connect cura-slicer:removable-media
	sudo snap connect cura-slicer:mount-observe
}

install_zsh () {
	sudo apt install -y git zsh ranger
	
	if [ ! -d $HOME/zsh-config ]; then
		git clone https://bitbucket.org/Vifon/zsh-config.git $HOME/zsh-config
	fi

	cd $HOME/zsh-config
	git submodule update --init
	./install.sh
	

	if [ "$(basename $(echo $SHELL))" != "zsh" ]; then
		chsh -s $(which zsh)
	fi

	if [ ! -d $HOME/.fzf ]; then
		git clone --depth 1 https://github.com/junegunn/fzf.git $HOME/.fzf
	fi
	~/.fzf/install --all
	[ ! -f $HOME/.zshrc.local ] && cp $TOP/.zshrc.local $HOME/.zshrc.local
        cd $(dirname $(readlink -f ~/.zshrc))
        git apply $TOP/zshrc.patch || true

}

for opt in "$@"; do
  case $opt in
    --upgrade)
      upgrade_system
      ;;
    --common)
      install_common_apps
      ;;
    --docker)
      install_docker
      ;;
    --zsh)
      install_zsh
      ;;
  esac
done

